create table
  public.clubs (
    id bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "updatedAt" timestamp without time zone null,
    name text not null,
    constraint club_pkey primary key (id),
    constraint club_name_key unique (name)
  ) tablespace pg_default;