create table
  public.events (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp without time zone null,
    name text null,
    host uuid null default gen_random_uuid (),
    start_time timestamp without time zone null,
    end_time timestamp without time zone null,
    location bigint null,
    constraint events_pkey primary key (id),
    constraint events_host_fkey foreign key (host) references users (id) on update cascade on delete cascade,
    constraint events_location_fkey foreign key (location) references locations (id) on update cascade on delete set null
  ) tablespace pg_default;