create table
  public.locations (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp without time zone null,
    name text null,
    address text null,
    constraint locations_pkey primary key (id)
  ) tablespace pg_default;